name: python ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix :
        python-version: [3.13, 3.12]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependecies
        run: |
          cd python-app
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run test 
        run: |
          cd python-app/
          python -m unittest discover 

      
      - name: notify us on success
        run: echo "Test passed on Python ${{ matrix.python-version }}  "
        if: success()